server:
  port: 8092
 
spring:
  datasource:
    url: jdbc:sqlserver://192.168.18.7:60741;databaseName=PESSOA_DB;user=sa;password=162243
    username: sa
    password: 162243
  jpa:
    show-sql: true 
    properties:
      hibernate:
        format_sql: true
